---

- name: prepare
  ansible.builtin.include_tasks: prepare.yaml
  tags:
    - users

# - name: remove users
#   ansible.builtin.include_tasks: remove_users.yaml
#   tags:
#     - users_remove

- name: add users
  ansible.builtin.include_tasks: add_users.yaml
  tags:
    - users_add

...
