---

- name: check if state are defined and valid
  ansible.builtin.set_fact:
    non_valid_users: "{{ users | validate_state }}"

- name: result for validation
  when:
    - non_valid_users is defined
    - non_valid_users | count > 0
  block:
    - name: result for validation
      ansible.builtin.debug:
        msg: "{{ non_valid_users | default([]) }}"

    - name: Fail when username or user state are not defined
      ansible.builtin.assert:
        that:
          - non_valid_users is defined
          - non_valid_users | count == 0
        quiet: true

- name: define absent users
  ansible.builtin.set_fact:
    absent_users: "{{ users | user_state(state='absent') }}"

- name: define present users
  ansible.builtin.set_fact:
    present_users: "{{ (users | difference(absent_users)) }}"


...
