---

- name: remove users
  ansible.builtin.user:
    name: "{{ item.username }}"
    state: absent
  loop:
    "{{ absent_users }}"
  loop_control:
    label: "username: {{ item.username }}"

- name: remove home directory
  ansible.builtin.file:
    path: "/home/{{ item.username }}"
    state: absent
  loop:
    "{{ absent_users }}"
  loop_control:
    label: "username: {{ item.username }}"

- name: remove central stored authorized keys
  ansible.builtin.file:
    path: "{{ item.ssh_key_directory }}/{{ item.username }}"
    state: absent
  when:
    - item.ssh_key is defined
    - item.ssh_key_directory is defined
    - item.ssh_key_directory | length > 0
  loop:
    "{{ absent_users }}"
  loop_control:
    label: "username: {{ item.username }}"

- name: remove user sudoers file and validate
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^{{ item.username }} '
    line: '{{ item.username }}'
    validate: 'visudo -cf %s'
  environment:
    PATH: /usr/sbin:/usr/local/sbin:/sbin
  when:
    - not item.use_sudo | default(false)
  loop:
    "{{ absent_users }}"
  loop_control:
    label: "username: {{ item.username }}"

...
