---

- name: create users
  hosts: instance
  any_errors_fatal: false
  become: false

  roles:
    - role: ansible-users


- name: remove user
  hosts: instance
  any_errors_fatal: false
  become: false

  vars:
    users:
      - username: blonde_feared
        state: absent

  roles:
    - role: ansible-users

...
