---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''
  roles:
    - role: ansible-users
      vars:
        users:
          - username: foo.bar
            update_password: always
            comment: Foo Bar
            shell: /bin/bash
            use_sudo: true
            use_sudo_nopass: true
            user_state: present
